"""
FlyMyByte — Unified dnsmasq Config Manager

Единый генератор конфигурации dnsmasq для всех bypass-списков и AI-доменов.
Заменяет: unblock_dnsmasq.sh, dns_spoofing.py generate_config.

Использование:
    from core.dnsmasq_manager import DnsmasqManager

    mgr = DnsmasqManager()
    mgr.generate_bypass_config()     # из всех .txt списков
    mgr.generate_ai_config()          # из ai-domains.txt
    mgr.generate_all()                # оба сразу
    mgr.restart_dnsmasq()             # применить
"""
import os
import re
import logging
import subprocess
import shutil
from typing import List, Dict, Tuple, Set, Optional

from .constants import DNSMASQ_CONFIG, DNSMASQ_AI_CONFIG, UNBLOCK_DIR, AI_DOMAINS_LIST, VPN_DNS_PORT, IPSET_MAP

logger = logging.getLogger(__name__)

# Пути
DNSMASQ_BYPASS_CONF = '/opt/etc/unblock.dnsmasq'
DNSMASQ_INIT_SCRIPT = '/opt/etc/init.d/S56dnsmasq'
DNSMASQ_TEMPLATE = '/opt/etc/web_ui/resources/config/dnsmasq.conf'


class DnsmasqManager:
    """Менеджер конфигурации dnsmasq."""

    def __init__(self, unblock_dir: str = UNBLOCK_DIR):
        self._unblock_dir = unblock_dir
        self._ai_domains_file = AI_DOMAINS_LIST

    # =========================================================================
    # DOMAIN LOADING
    # =========================================================================

    def load_domains_from_file(self, filepath: str) -> Set[str]:
        """
        Загрузить домены из файла.

        Args:
            filepath: Путь к файлу с доменами

        Returns:
            Set[str]: Множество уникальных доменов
        """
        domains = set()
        if not os.path.exists(filepath):
            return domains

        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                for line in f:
                    line = line.strip()
                    # Пропускаем комментарии и пустые строки
                    if not line or line.startswith('#'):
                        continue
                    # Пропускаем IP-адреса
                    if line[0].isdigit():
                        continue
                    # Валидируем домен
                    if self._is_valid_domain(line):
                        domains.add(line.lower())
        except Exception as e:
            logger.error(f"Error loading domains from {filepath}: {e}")

        logger.debug(f"Loaded {len(domains)} domains from {filepath}")
        return domains

    def load_all_bypass_domains(self) -> Dict[str, Set[str]]:
        """
        Загрузить домены из ВСЕХ bypass-файлов (.txt).
        
        Использует IPSET_MAP для маппинга filename -> ipset_name.

        Returns:
            Dict[str, Set[str]]: {ipset_name: set_of_domains}
        """
        result = {}
        if not os.path.exists(self._unblock_dir):
            return result

        # Используем IPSET_MAP: filename (без .txt) -> ipset_name
        for filename_stem, ipset_name in IPSET_MAP.items():
            filepath = os.path.join(self._unblock_dir, f"{filename_stem}.txt")
            domains = self.load_domains_from_file(filepath)
            if domains:
                result[ipset_name] = domains

        logger.info(f"Loaded bypass domains from {len(result)} files")
        return result

    def load_ai_domains(self) -> Set[str]:
        """Загрузить AI-домены из файла."""
        return self.load_domains_from_file(self._ai_domains_file)

    # =========================================================================
    # CONFIG GENERATION
    # =========================================================================

    def generate_bypass_config(self) -> Tuple[bool, str]:
        """
        Сгенерировать конфиг для bypass-доменов (unblock.dnsmasq).

        NOTE: ipset= директивы УБРАНЫ в пользу direct DNS resolve.
        Теперь домены резолвятся при добавлении в bypass (proactive).
        Оставили только комментарии для совместимости.

        Returns:
            Tuple[bool, str]: (success, message)
        """
        all_domains = self.load_all_bypass_domains()
        if not all_domains:
            try:
                with open(DNSMASQ_BYPASS_CONF, 'w') as f:
                    f.write('# Bypass domains config (empty)\n')
                return True, "No bypass domains found, empty config created"
            except Exception as e:
                return False, str(e)

        lines = [
            '# Auto-generated bypass domains config',
            '# NOTE: ipset= directives removed - bypass uses direct DNS resolve',
            '# See: dns_ops.resolve_domains_for_ipset() for proactive resolution',
            ''
        ]
        total_domains = 0

        for ipset_name, domains in all_domains.items():
            lines.append(f'# === {ipset_name} ({len(domains)} domains) ===')
            lines.append(f'# Domains resolved via: resolve_domains_for_ipset()')
            total_domains += len(domains)
            lines.append('')

        try:
            temp_path = DNSMASQ_BYPASS_CONF + '.tmp'
            with open(temp_path, 'w', encoding='utf-8') as f:
                f.write('\n'.join(lines) + '\n')
            os.replace(temp_path, DNSMASQ_BYPASS_CONF)
            logger.info(f"Generated bypass config: {total_domains} domains (ipset= directives disabled)")
            return True, f"Generated {total_domains} domains across {len(all_domains)} ipsets (direct resolve)"
        except Exception as e:
            logger.error(f"Failed to write bypass config: {e}")
            return False, str(e)

    def generate_ai_config(self) -> Tuple[bool, str]:
        """
        Сгенерировать конфиг для AI-доменов (unblock-ai.dnsmasq).

        Формат:
            server=/aistudio.google.com/127.0.0.1#40500

        Returns:
            Tuple[bool, str]: (success, message)
        """
        domains = self.load_ai_domains()
        if not domains:
            # Создаём пустой файл
            try:
                with open(DNSMASQ_AI_CONFIG, 'w') as f:
                    f.write('# AI domains config (empty)\n')
                return True, "No AI domains found, empty config created"
            except Exception as e:
                return False, str(e)

        lines = ['# Auto-generated AI domains config', '']
        for domain in sorted(domains):
            lines.append(f'server=/{domain}/127.0.0.1#{VPN_DNS_PORT}')

        try:
            temp_path = DNSMASQ_AI_CONFIG + '.tmp'
            with open(temp_path, 'w', encoding='utf-8') as f:
                f.write('\n'.join(lines) + '\n')
            os.replace(temp_path, DNSMASQ_AI_CONFIG)
            logger.info(f"Generated AI config: {len(domains)} domains")
            return True, f"Generated {len(domains)} AI domains"
        except Exception as e:
            logger.error(f"Failed to write AI config: {e}")
            return False, str(e)

    def _sanitize_dnsmasq_conf(self):
        """
        Удалить устаревшие/битые строки из dnsmasq.conf.

        Исправляет:
        - ipset=/onion/unblocktor (удалён в v2.7.0)
        - server=/onion/... (Tor удалён)
        - server=127.0.0.1#40500 (VPN DNS — ломает интернет если VPN не работает)
        """
        config_path = DNSMASQ_CONFIG
        if not os.path.exists(config_path):
            return

        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                lines = f.readlines()

            # Строки которые нужно удалить
            obsolete_patterns = [
                'ipset=/onion/unblocktor',
                'ipset=/onion/unblock4-tor',
                'ipset=/onion/unblock6-tor',
                'conf-file=/opt/etc/unblock-tor.dnsmasq',
                'server=127.0.0.1#40500',  # FIX: VPN DNS который ломает интернет
            ]

            cleaned = []
            removed = 0
            for line in lines:
                stripped = line.strip()
                is_obsolete = any(pattern in stripped for pattern in obsolete_patterns)
                if is_obsolete:
                    logger.info(f"[SANITIZE] Removed obsolete line: {stripped}")
                    removed += 1
                else:
                    cleaned.append(line)

            if removed > 0:
                # Сохраняем только если были изменения
                with open(config_path, 'w', encoding='utf-8') as f:
                    f.writelines(cleaned)
                logger.info(f"[SANITIZE] Removed {removed} obsolete lines from dnsmasq.conf")

        except Exception as e:
            logger.warning(f"[SANITIZE] Failed to sanitize dnsmasq.conf: {e}")

    def generate_all(self) -> Tuple[bool, str]:
        """
        Сгенерировать ОБА конфига (bypass + AI).

        Returns:
            Tuple[bool, str]: (success, message)
        """
        bypass_ok, bypass_msg = self.generate_bypass_config()
        ai_ok, ai_msg = self.generate_ai_config()

        if bypass_ok and ai_ok:
            return True, f"OK: {bypass_msg}; {ai_msg}"
        elif bypass_ok:
            return True, f"Partial: {bypass_msg}; AI failed: {ai_msg}"
        elif ai_ok:
            return True, f"Partial: Bypass failed: {bypass_msg}; {ai_msg}"
        else:
            return False, f"Failed: {bypass_msg}; {ai_msg}"

    # =========================================================================
    # DNSMASQ RESTART
    # =========================================================================

    def _check_process(self, pattern: str) -> bool:
        """Проверить наличие процесса через /proc (BusyBox-совместимо)."""
        try:
            for pid_dir in os.listdir('/proc'):
                if not pid_dir.isdigit():
                    continue
                cmdline_path = f'/proc/{pid_dir}/cmdline'
                try:
                    with open(cmdline_path, 'rb') as f:
                        cmdline = f.read().decode('utf-8', errors='ignore')
                        if re.search(pattern, cmdline):
                            return True
                except (FileNotFoundError, PermissionError):
                    continue
            return False
        except Exception as e:
            logger.warning(f"Error checking process '{pattern}': {e}")
            return False

    def restart_dnsmasq(self, signal_only: bool = False) -> Tuple[bool, str]:
        """
        Перезапустить dnsmasq для применения новых конфигов.

        Args:
            signal_only: Если True, использовать SIGHUP вместо полного рестарта

        Returns:
            Tuple[bool, str]: (success, message)
        """
        if signal_only:
            # Быстрый SIGHUP (не останавливает dnsmasq)
            try:
                # Найти PID dnsmasq через /proc
                for pid_dir in os.listdir('/proc'):
                    if not pid_dir.isdigit():
                        continue
                    cmdline_path = f'/proc/{pid_dir}/cmdline'
                    try:
                        with open(cmdline_path, 'rb') as f:
                            cmdline = f.read().decode('utf-8', errors='ignore')
                            if 'dnsmasq' in cmdline:
                                subprocess.run(['kill', '-HUP', pid_dir], capture_output=True, timeout=5)
                                logger.info("Sent SIGHUP to dnsmasq")
                                return True, "SIGHUP sent to dnsmasq"
                    except (FileNotFoundError, PermissionError):
                        continue
            except Exception as e:
                logger.error(f"SIGHUP failed: {e}")

        # Полный рестарт
        if os.path.exists(DNSMASQ_INIT_SCRIPT):
            # Сначала исправляем устаревшие строки в dnsmasq.conf
            self._sanitize_dnsmasq_conf()

            # Затем тестируем конфиг на корректность
            if os.path.exists(DNSMASQ_CONFIG):
                try:
                    test_result = subprocess.run(
                        ['dnsmasq', '--test'],
                        capture_output=True, text=True, timeout=5
                    )
                    if test_result.returncode != 0:
                        logger.error(f"dnsmasq config test failed: {test_result.stderr}")
                        return False, f"Config test failed: {test_result.stderr.strip()}"
                    logger.info("dnsmasq config test passed")
                except FileNotFoundError:
                    logger.warning("dnsmasq binary not found, skipping config test")
                except Exception as e:
                    logger.warning(f"Config test error: {e}")

            try:
                result = subprocess.run(
                    ['sh', DNSMASQ_INIT_SCRIPT, 'restart'],
                    capture_output=True, text=True, timeout=15
                )
                if result.returncode == 0:
                    logger.info("dnsmasq restarted successfully")
                    return True, "dnsmasq restarted"
                else:
                    logger.error(f"dnsmasq restart failed: {result.stderr.strip()}")
                    return False, result.stderr.strip()
            except Exception as e:
                logger.error(f"dnsmasq restart error: {e}")
                return False, str(e)

        return False, "dnsmasq init script not found"

    def restart_dnsmasq_with_retry(self, retries: int = 3, delay: int = 2) -> Tuple[bool, str]:
        """
        Перезапустить dnsmasq с повторными попытками.

        Args:
            retries: Количество попыток
            delay: Задержка между попытками (сек)

        Returns:
            Tuple[bool, str]: (success, message)
        """
        import time

        for attempt in range(1, retries + 1):
            ok, msg = self.restart_dnsmasq()
            if ok:
                return True, msg

            logger.warning(f"dnsmasq restart attempt {attempt}/{retries} failed: {msg}")
            if attempt < retries:
                time.sleep(delay)

        return False, f"All {retries} attempts failed"

    # =========================================================================
    # VALIDATION
    # =========================================================================

    def test_config(self) -> Tuple[bool, str]:
        """
        Проверить валидность dnsmasq конфигурации.

        Returns:
            Tuple[bool, str]: (valid, message)
        """
        if not os.path.exists(DNSMASQ_CONFIG):
            return False, "dnsmasq.conf not found"

        try:
            result = subprocess.run(
                ['dnsmasq', '--test'],
                capture_output=True, text=True, timeout=10
            )
            if result.returncode == 0:
                return True, "Config is valid"
            return False, result.stderr.strip()
        except FileNotFoundError:
            return True, "dnsmasq binary not found (skip test)"
        except Exception as e:
            return False, str(e)

    @staticmethod
    def _is_valid_domain(domain: str) -> bool:
        """
        Простая валидация домена.

        Args:
            domain: Доменное имя

        Returns:
            bool: True если домен валиден
        """
        if not domain or len(domain) > 253:
            return False
        return bool(re.match(r'^[a-z0-9]([a-z0-9\-\.]*[a-z0-9])?$', domain))

    # =========================================================================
    # STATUS
    # =========================================================================

    def get_status(self) -> Dict:
        """
        Получить статус dnsmasq и конфигов.

        Returns:
            Dict: Статус
        """
        status = {
            'dnsmasq_running': False,
            'dnsmasq_port': None,
            'bypass_domains': 0,
            'ai_domains': 0,
            'config_valid': False,
        }

        # Проверяем запущен ли dnsmasq через /proc
        status['dnsmasq_running'] = self._check_process('dnsmasq')

        # Считаем домены
        bypass_domains = self.load_all_bypass_domains()
        status['bypass_domains'] = sum(len(d) for d in bypass_domains.values())

        ai_domains = self.load_ai_domains()
        status['ai_domains'] = len(ai_domains)

        # Проверяем конфиг
        valid, _ = self.test_config()
        status['config_valid'] = valid

        return status


# =============================================================================
# MODULE-LEVEL CONVENIENCE FUNCTIONS
# =============================================================================

def get_dnsmasq_manager() -> DnsmasqManager:
    """Получить экземпляр менеджера (singleton)."""
    if not hasattr(get_dnsmasq_manager, '_instance'):
        get_dnsmasq_manager._instance = DnsmasqManager()
    return get_dnsmasq_manager._instance


def generate_all_configs() -> Tuple[bool, str]:
    """Сгенерировать все конфиги и перезапустить dnsmasq."""
    mgr = get_dnsmasq_manager()
    ok, msg = mgr.generate_all()
    if ok:
        mgr.restart_dnsmasq()
    return ok, msg
