#!/bin/sh
# S99unblock - Скрипт автоматического заполнения множества unblock при загрузке

case "$1" in
  start)
    echo "Starting unblock ipset..."
    /opt/bin/unblock_ipset.sh
    echo "Setting up iptables redirect rules..."
    /opt/etc/ndm/netfilter.d/100-redirect.sh
    ;;
  stop)
    echo "Stopping unblock ipset..."
    # Очистка множеств (опционально)
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
