#!/bin/sh
# unblock_dnsmasq.sh - Optimized version with parallel generation
# Includes AI domains DNS spoofing support

mkdir -p /opt/var/log
LOGFILE="/opt/var/log/unblock_dnsmasq.log"
TAG="unblock_dnsmasq"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [$TAG] $1" >> "$LOGFILE"
}

log_error() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [$TAG] ERROR: $1" >> "$LOGFILE"
}

log "=== Script started ==="

# Get DNS-over-TLS port from web config
DNS_PORT="40500"
if [ -f "/opt/etc/web_ui/.env" ]; then
    DNS_PORT=$(grep "^dnsovertlsport=" /opt/etc/web_ui/.env 2>/dev/null | cut -d'=' -f2 | tr -d ' ')
    [ -z "$DNS_PORT" ] && DNS_PORT="40500"
fi
log "DNS-over-TLS port: $DNS_PORT"

# Clear dnsmasq config
log "Clearing /opt/etc/unblock.dnsmasq"
cat /dev/null > /opt/etc/unblock.dnsmasq

# Clear AI domains config
log "Clearing /opt/etc/unblock-ai.dnsmasq"
cat /dev/null > /opt/etc/unblock-ai.dnsmasq

# Function to generate config for a single file
generate_config() {
    local file="$1"
    local setname="$2"
    local temp_config="$3"

    if [ ! -f "$file" ]; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') [$TAG] WARNING: $file not found" >> "$LOGFILE"
        return
    fi

    local domain_count=0
    local skipped=0

    # Process file, skipping comments and empty lines
    while read -r line || [ -n "$line" ]; do
        [ -z "$line" ] && { skipped=$((skipped + 1)); continue; }
        [ "${line#?}" = "#" ] && { skipped=$((skipped + 1)); continue; }

        # Skip IP addresses (only process domains)
        if echo "$line" | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
            skipped=$((skipped + 1))
            continue
        fi

        # Handle wildcard domains (keep as is, dnsmasq ignores leading dots)
        echo "ipset=/$line/$setname" >> "$temp_config"
        # NOTE: Do NOT add server= for bypass domains.
        # dnsmasq resolves via upstream DNS (8.8.8.8), and ipset= automatically
        # adds the resolved IP to ipset. Server=127.0.0.1#40500 (stubby via proxy)
        # causes SERVFAIL when proxy is down, killing DNS for bypass domains.
        # VPN DNS traffic is routed via iptables REDIRECT to proxy port.
        domain_count=$((domain_count + 1))
    done < "$file"

    echo "$(date '+%Y-%m-%d %H:%M:%S') [$TAG] Generated $domain_count domain rules for $setname (skipped $skipped lines)" >> "$LOGFILE"
}

# Process files in parallel
temp_dir="/tmp/dnsmasq_config_$$"
mkdir -p "$temp_dir"
log "Temp dir: $temp_dir"

i=0

log "Processing predefined files..."

# Process predefined files
for entry in "/opt/etc/unblock/shadowsocks.txt:unblocksh" "/opt/etc/unblock/vless.txt:unblockvless" "/opt/etc/unblock/trojan.txt:unblocktroj"; do
    file=$(echo "$entry" | cut -d: -f1)
    setname=$(echo "$entry" | cut -d: -f2)

    temp_config="$temp_dir/config_$i.txt"
    > "$temp_config"

    log "  Starting: $file -> $setname"
    generate_config "$file" "$setname" "$temp_config" &
    i=$((i + 1))
done

# Add and process VPN files
if ls /opt/etc/unblock/vpn-*.txt >/dev/null 2>&1; then
    log "Processing VPN files..."
    for vpn_file in /opt/etc/unblock/vpn-*.txt; do
        if [ -f "$vpn_file" ]; then
            vpn_name=$(basename "$vpn_file" .txt)
            setname="unblock$vpn_name"
            
            temp_config="$temp_dir/config_$i.txt"
            > "$temp_config"
            
            log "  Starting: $vpn_file -> $setname"
            generate_config "$vpn_file" "$setname" "$temp_config" &
            i=$((i + 1))
        fi
    done
else
    log "No VPN files found"
fi

# Wait for all background jobs
log "Waiting for all generators to complete..."
wait

# Combine all configs
if ls "$temp_dir"/config_*.txt >/dev/null 2>&1; then
    cat "$temp_dir"/config_*.txt >> /opt/etc/unblock.dnsmasq
    total_lines=$(wc -l < /opt/etc/unblock.dnsmasq)
    log "Combined config: $total_lines lines written to /opt/etc/unblock.dnsmasq"
else
    log_error "No config files generated in $temp_dir"
fi

# Cleanup
rm -rf "$temp_dir"

# AI Domains DNS Spoofing
AI_DOMAINS_FILE="/opt/etc/unblock/ai-domains.txt"
if [ -f "$AI_DOMAINS_FILE" ]; then
    log "Processing AI domains from $AI_DOMAINS_FILE"
    echo "# AI Domains DNS Spoofing" >> /opt/etc/unblock-ai.dnsmasq
    echo "# Generated by unblock_dnsmasq.sh" >> /opt/etc/unblock-ai.dnsmasq
    echo "" >> /opt/etc/unblock-ai.dnsmasq

    # Re-read DNS port (in case it changed)
    DNS_PORT="40500"
    if [ -f "/opt/etc/web_ui/.env" ]; then
        DNS_PORT=$(grep "^dnsovertlsport=" /opt/etc/web_ui/.env 2>/dev/null | cut -d'=' -f2 | tr -d ' ')
        [ -z "$DNS_PORT" ] && DNS_PORT="40500"
    fi

    ai_domain_count=0
    ai_skipped=0

    while read -r line || [ -n "$line" ]; do
        [ -z "$line" ] && { ai_skipped=$((ai_skipped + 1)); continue; }
        [ "${line:0:1}" = "#" ] && { ai_skipped=$((ai_skipped + 1)); continue; }

        # Skip IP addresses
        if echo "$line" | grep -Eq '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'; then
            ai_skipped=$((ai_skipped + 1))
            continue
        fi

        # Handle wildcard domains (convert to base domain)
        case "$line" in
            \*.* )
                domain="${line#\*.}"
                ;;
            * )
                domain="$line"
                ;;
        esac

        # Add dnsmasq rules for AI domains (route through VPN DNS)
        echo "server=/$domain/127.0.0.1#$DNS_PORT" >> /opt/etc/unblock-ai.dnsmasq
        ai_domain_count=$((ai_domain_count + 1))
    done < "$AI_DOMAINS_FILE"

    ai_total_lines=$(wc -l < /opt/etc/unblock-ai.dnsmasq)
    log "AI domains: $ai_domain_count domains processed ($ai_skipped skipped), $ai_total_lines total lines"
else
    log "AI domains file not found: $AI_DOMAINS_FILE"
fi

# Restart dnsmasq
log "Restarting dnsmasq..."
if /opt/etc/init.d/S56dnsmasq restart >> "$LOGFILE" 2>&1; then
    log "dnsmasq restarted successfully"
else
    log_error "dnsmasq restart failed"
fi

log "=== Script completed ==="
echo "✅ Dnsmasq config generated" | tee -a "$LOGFILE"
